nyc_taxi_lakehouse:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: tyczfui-mhc52087
      user: nyc_taxi_user
      password: "Lakehouse@2024!"
      role: nyc_taxi_role
      warehouse: nyc_taxi_wh
      database: nyc_taxi_lakehouse
      schema: raw_data
      threads: 4
      client_session_keep_alive: false
      query_tag: dbt_dev

    prod:
      type: snowflake
      account: tyczfui-mhc52087
      user: nyc_taxi_user
      password: "Lakehouse@2024!"
      role: nyc_taxi_role
      warehouse: nyc_taxi_wh
      database: nyc_taxi_lakehouse
      schema: raw_data
      threads: 8
      client_session_keep_alive: false
      query_tag: dbt_prod
